### ISSUE TITLE
PP-OCRv3 文本检测

### ISSUE THREAD

**Issue by guishilike** [yangy996/PaddleOCR#1]
请问支持ch_PP-OCRv3的文本检测吗

**Comment by yangy996** [comment]
支持，按着流程自行修改就可以了

**Comment by guishilike** [comment]
对于CombinedLoss的话 只需要更改DistillationDilaDBLoss，其余DistillationDMLLoss，DistillationDBLoss这些都不需要改动 是吗

**Comment by yangy996** [comment]
这个模式的我还没做适配

**Comment by guishilike** [comment]
现在ch_PP-OCRv3的不都是这样吗？
![image](https://user-images.githubusercontent.com/51023060/194746281-38261a0c-1e1d-4cab-b10a-f801802fe173.png)
也就是是说现在这个只支持类似det_mv3_db.yml或者det_r50_vd_db.yml这样的配置训练吗

**Comment by yangy996** [comment]
不是啊，还有单独的student模式
![image](https://user-images.githubusercontent.com/15188456/194746474-d74d0d6c-2d87-4a25-9d03-898253b7fdf3.png)

**Comment by guishilike** [comment]
可是这个不是只有neck那块有点区别

**Comment by yangy996** [comment]
> 可是这个不是只有neck那块有点区别

student.yml只是对neck模块做了升级，其他地方没有改动
