### ISSUE TITLE
分类精度

### ISSUE THREAD

**Issue by guishilike** [yangy996/PaddleOCR#3]
我试验了分类效果，感觉针对复杂场景的精度不是很高。直接采用DBNet文本分割网络去做分类效果是不是不太好，我看飞浆他们为了提高精度，把一些信息合并了。
![image](https://user-images.githubusercontent.com/51023060/196587152-ba320163-2632-4221-9bea-5c02daa4f600.png)
模型该如何提高精度？

**Comment by yangy996** [comment]
你是不是哪里改的不对，我这边训练出来的模型效果非常好，建议你试试博客里的模型
