### ISSUE TITLE
推理模型转换后，失去class信息

### ISSUE THREAD

**Issue by LUOQING1994** [yangy996/PaddleOCR#4]
### 问题描述
模型训练完毕，使用inter_det.py进行预测，可正常在身份证上显示标签和检测框，运行export_model.py后，得到推理模型，但使用predict_det.py进行推理时，db_postprocess.py中只能得到预测框，如下图所示，
![image](https://user-images.githubusercontent.com/20340633/203302739-44da31b6-2ab1-488e-a5ac-4a014b72667c.png)
在打印结果中，并没有classes的信息
### 期望结果
推理结果和预测结果都能打印出classes信息

**Comment by yangy996** [comment]
predict_det.py中def __call__(self, img, cls=False):，cls改成True就会输出label

**Comment by LUOQING1994** [comment]
> predict_det.py中def **call**(self, img, cls=False):，cls改成True就会输出label

十分感谢！我是在2.6版本上进行修改，看代码时疏忽了这个地方
